# This is a basic workflow to help you get started with Actions

name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10-19/3 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@release/2022-31
    - name: execute py script
      run: python main.py
