# This is a basic workflow to help you get started with Actions

name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10-19/3 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: running
      run: python.py
   
         
