# This is a basic workflow to help you get started with Actions

name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Running
      run: |
        echo "Running!"
