# This is a basic workflow to help you get started with Actions

name: python.py
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
 schedule:
    - cron: '0 10-19/2 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: running
      run: |
         python3 python.py
   
         
