# This is a basic workflow to help you get started with Actions

name: python.py
on:
  push:
    branches:
      - master
  schedule:
    - cron: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: running
      run: |
         python.py
   
         
